In [1]:
import pandas as pd
from config import password
from config import port
from config import host

In [2]:
players_df = pd.read_csv('players.csv')

In [3]:
map_1_df = players_df[[
    'date',
    'player_name',
    'team',
    'opponent', 
    'player_id', 
    'match_id',
    'event_id',
    'best_of',
    'map_1',
    'm1_kills',
    'm1_assists',
    'm1_deaths',
    'm1_hs',
    'm1_flash_assists',
    'm1_kast',
    'm1_kddiff',
    'm1_adr',
    'm1_fkdiff',
    'm1_rating']].copy()
map_1_df

,date,player_name,team,opponent,player_id,match_id,event_id,best_of,map_1,m1_kills,m1_assists,m1_deaths,m1_hs,m1_flash_assists,m1_kast,m1_kddiff,m1_adr,m1_fkdiff,m1_rating
0,2020-02-26,Brehze,Evil Geniuses,Liquid,9136,2339385,4901,3,Overpass,11,3,18,5,0.0,65.2,-7,60.8,-1,0.70
1,2020-02-26,CeRq,Evil Geniuses,Liquid,11219,2339385,4901,3,Overpass,11,2,17,4,2.0,60.9,-6,68.9,-1,0.75
2,2020-02-26,EliGE,Liquid,Evil Geniuses,8738,2339385,4901,3,Overpass,15,3,12,9,0.0,69.6,3,77.0,3,1.32
3,2020-02-26,Ethan,Evil Geniuses,Liquid,10671,2339385,4901,3,Overpass,11,1,15,6,1.0,65.2,-4,60.7,-2,0.73
4,2020-02-26,NAF,Liquid,Evil Geniuses,8520,2339385,4901,3,Overpass,10,5,12,3,3.0,65.2,-2,51.5,0,0.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383312,2015-10-07,kIMERA,ExAequo,RIP Fonty,7607,2298497,1957,2,Cobblestone,15,0,4,2,NaN,NaN,11,NaN,1,1.63
383313,2015-10-07,morphiw0w,ExAequo,RIP Fonty,9752,2298497,1957,2,Cobblestone,14,1,6,7,NaN,NaN,8,NaN,0,1.32
383314,2015-10-07,overfly,RIP Fonty,ExAequo,7698,2298497,1957,2,Cobblestone,8,1,16,3,NaN,NaN,-8,NaN,-1,0.44
383315,2015-10-07,simozor,RIP Fonty,ExAequo,9753,2298497,1957,2,Cobblestone,5,0,17,2,NaN,NaN,-12,NaN,0,0.25
383316,2015-10-07,xullE,RIP Fonty,ExAequo,9754,2298497,1957,2,Cobblestone,5,1,16,3,NaN,NaN,-11,NaN,0,0.33

In [4]:
map_1_df = map_1_df.dropna()

In [5]:
map_2_df = players_df[[
    'date',
    'player_name',
    'team',
    'opponent', 
    'player_id', 
    'match_id',
    'event_id',
    'best_of',
    'map_2',
    'm2_kills',
    'm2_assists',
    'm2_deaths',
    'm2_hs',
    'm2_flash_assists',
    'm2_kast',
    'm2_kddiff',
    'm2_adr',
    'm2_fkdiff',
    'm2_rating']].copy()
map_2_df

,date,player_name,team,opponent,player_id,match_id,event_id,best_of,map_2,m2_kills,m2_assists,m2_deaths,m2_hs,m2_flash_assists,m2_kast,m2_kddiff,m2_adr,m2_fkdiff,m2_rating
0,2020-02-26,Brehze,Evil Geniuses,Liquid,9136,2339385,4901,3,Nuke,30.0,7.0,24.0,16.0,0.0,73.5,6.0,99.2,6.0,1.38
1,2020-02-26,CeRq,Evil Geniuses,Liquid,11219,2339385,4901,3,Nuke,26.0,6.0,19.0,8.0,1.0,76.5,7.0,80.1,3.0,1.24
2,2020-02-26,EliGE,Liquid,Evil Geniuses,8738,2339385,4901,3,Nuke,24.0,3.0,24.0,14.0,0.0,64.7,0.0,72.9,-1.0,0.97
3,2020-02-26,Ethan,Evil Geniuses,Liquid,10671,2339385,4901,3,Nuke,22.0,3.0,21.0,8.0,1.0,70.6,1.0,67.9,-2.0,1.00
4,2020-02-26,NAF,Liquid,Evil Geniuses,8520,2339385,4901,3,Nuke,29.0,6.0,21.0,16.0,0.0,82.4,8.0,101.9,0.0,1.35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383312,2015-10-07,kIMERA,ExAequo,RIP Fonty,7607,2298497,1957,2,Cache,15.0,2.0,13.0,6.0,NaN,NaN,2.0,NaN,1.0,1.06
383313,2015-10-07,morphiw0w,ExAequo,RIP Fonty,9752,2298497,1957,2,Cache,12.0,5.0,16.0,2.0,NaN,NaN,-4.0,NaN,0.0,0.79
383314,2015-10-07,overfly,RIP Fonty,ExAequo,7698,2298497,1957,2,Cache,20.0,3.0,18.0,5.0,NaN,NaN,2.0,NaN,3.0,1.06
383315,2015-10-07,simozor,RIP Fonty,ExAequo,9753,2298497,1957,2,Cache,13.0,7.0,19.0,7.0,NaN,NaN,-6.0,NaN,-4.0,0.68
383316,2015-10-07,xullE,RIP Fonty,ExAequo,9754,2298497,1957,2,Cache,9.0,1.0,19.0,4.0,NaN,NaN,-10.0,NaN,0.0,0.52

In [6]:
map_2_df = map_2_df.dropna()

In [7]:
map_3_df = players_df[[
    'date',
    'player_name',
    'team',
    'opponent', 
    'player_id', 
    'match_id',
    'event_id',
    'best_of',
    'map_3',
    'm3_kills',
    'm3_assists',
    'm3_deaths',
    'm3_hs',
    'm3_flash_assists',
    'm3_kast',
    'm3_kddiff',
    'm3_adr',
    'm3_fkdiff',
    'm3_rating']].copy()
map_3_df

,date,player_name,team,opponent,player_id,match_id,event_id,best_of,map_3,m3_kills,m3_assists,m3_deaths,m3_hs,m3_flash_assists,m3_kast,m3_kddiff,m3_adr,m3_fkdiff,m3_rating
0,2020-02-26,Brehze,Evil Geniuses,Liquid,9136,2339385,4901,3,Inferno,16.0,4.0,19.0,8.0,0.0,73.1,-3.0,71.6,-5.0,0.91
1,2020-02-26,CeRq,Evil Geniuses,Liquid,11219,2339385,4901,3,Inferno,17.0,2.0,18.0,6.0,1.0,53.8,-1.0,63.1,0.0,0.87
2,2020-02-26,EliGE,Liquid,Evil Geniuses,8738,2339385,4901,3,Inferno,16.0,4.0,15.0,5.0,1.0,69.2,1.0,85.2,-1.0,1.04
3,2020-02-26,Ethan,Evil Geniuses,Liquid,10671,2339385,4901,3,Inferno,10.0,1.0,18.0,4.0,0.0,57.7,-8.0,45.0,0.0,0.69
4,2020-02-26,NAF,Liquid,Evil Geniuses,8520,2339385,4901,3,Inferno,13.0,11.0,13.0,4.0,6.0,80.8,0.0,63.3,-1.0,0.98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383312,2015-10-07,kIMERA,ExAequo,RIP Fonty,7607,2298497,1957,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
383313,2015-10-07,morphiw0w,ExAequo,RIP Fonty,9752,2298497,1957,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
383314,2015-10-07,overfly,RIP Fonty,ExAequo,7698,2298497,1957,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
383315,2015-10-07,simozor,RIP Fonty,ExAequo,9753,2298497,1957,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
383316,2015-10-07,xullE,RIP Fonty,ExAequo,9754,2298497,1957,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
map_3_df = map_3_df.dropna()

In [9]:
map_3_df.columns

Index(['date', 'player_name', 'team', 'opponent', 'player_id', 'match_id',
       'event_id', 'best_of', 'map_3', 'm3_kills', 'm3_assists', 'm3_deaths',
       'm3_hs', 'm3_flash_assists', 'm3_kast', 'm3_kddiff', 'm3_adr',
       'm3_fkdiff', 'm3_rating'],
      dtype='object')

In [10]:
rename_column_headers = ['date',
    'player_name',
    'team', 
    'opponent',
    'player_id',
    'match_id',
    'event_id',
    'best_of',
    'map',
    'kills',
    'assists',
    'deaths',
    'hs',
    'flash_assists',
    'kast',
    'kddiff',
    'adr',
    'fkdiff',
    'rating']

# Change column headers
map_1_df.columns = (rename_column_headers)
map_2_df.columns = (rename_column_headers)
map_3_df.columns = (rename_column_headers)

In [11]:
frames = [map_1_df, map_2_df, map_3_df]

revised_players = pd.concat(frames)

In [30]:
player_running_averages = revised_players.sort_values(['player_id','map','date'])

In [31]:
player_running_averages

,date,player_name,team,opponent,player_id,match_id,event_id,best_of,map,kills,assists,deaths,hs,flash_assists,kast,kddiff,adr,fkdiff,rating
359523,2016-03-12,Friis,SK,FaZe,7,2301112,2124,1,Cache,34.0,5.0,29.0,3.0,0.0,75.0,5.0,63.8,1.0,1.08
280188,2017-04-18,Friis,Tricked,SFTO,7,2309816,2782,3,Cache,18.0,4.0,19.0,2.0,2.0,66.7,-1.0,63.4,-2.0,0.94
267010,2017-05-31,Friis,Tricked,PENTA,7,2311256,2872,3,Cache,17.0,2.0,20.0,6.0,1.0,64.0,-3.0,69.2,-2.0,0.84
255059,2017-07-11,Friis,Gux & Friends,ALTERNATE aTTaX,7,2312594,2879,1,Cache,16.0,3.0,15.0,7.0,0.0,73.1,1.0,61.0,-1.0,1.01
255131,2017-07-11,Friis,Gux & Friends,Gambit,7,2312579,2879,1,Cache,17.0,6.0,19.0,3.0,0.0,56.5,-2.0,76.4,2.0,0.98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
737,2020-02-23,rabbit,Titan,Medieval,20006,2339752,5230,3,Nuke,26.0,3.0,14.0,13.0,0.0,85.2,12.0,92.7,1.0,1.42
722,2020-02-23,boskacz,Wisla Krakow,BIG,20007,2339745,5150,1,Nuke,3.0,1.0,16.0,0.0,1.0,22.2,-13.0,19.7,-2.0,0.24
115,2020-02-27,Porky,LND,Rysix,20009,2339813,5233,1,Vertigo,14.0,0.0,16.0,7.0,0.0,57.9,-2.0,86.5,0.0,0.93
119,2020-02-27,shevi,LND,Rysix,20010,2339813,5233,1,Vertigo,6.0,1.0,17.0,5.0,0.0,57.9,-11.0,42.2,-1.0,0.50
153,2020-02-26,bichop,FREEROX,Sinisters,20011,2339810,5233,1,Mirage,13.0,3.0,19.0,9.0,0.0,57.7,-6.0,63.2,3.0,0.85

In [32]:
pk = player_running_averages[['player_id','match_id','date','map','kills','assists','deaths','hs','flash_assists','kast','kddiff','adr','fkdiff','rating']]

In [33]:
pk = pk.set_index('player_id')

In [34]:
pk

,match_id,date,map,kills,assists,deaths,hs,flash_assists,kast,kddiff,adr,fkdiff,rating
player_id,,,,,,,,,,,,,
7,2301112,2016-03-12,Cache,34.0,5.0,29.0,3.0,0.0,75.0,5.0,63.8,1.0,1.08
7,2309816,2017-04-18,Cache,18.0,4.0,19.0,2.0,2.0,66.7,-1.0,63.4,-2.0,0.94
7,2311256,2017-05-31,Cache,17.0,2.0,20.0,6.0,1.0,64.0,-3.0,69.2,-2.0,0.84
7,2312594,2017-07-11,Cache,16.0,3.0,15.0,7.0,0.0,73.1,1.0,61.0,-1.0,1.01
7,2312579,2017-07-11,Cache,17.0,6.0,19.0,3.0,0.0,56.5,-2.0,76.4,2.0,0.98
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20006,2339752,2020-02-23,Nuke,26.0,3.0,14.0,13.0,0.0,85.2,12.0,92.7,1.0,1.42
20007,2339745,2020-02-23,Nuke,3.0,1.0,16.0,0.0,1.0,22.2,-13.0,19.7,-2.0,0.24
20009,2339813,2020-02-27,Vertigo,14.0,0.0,16.0,7.0,0.0,57.9,-2.0,86.5,0.0,0.93
20010,2339813,2020-02-27,Vertigo,6.0,1.0,17.0,5.0,0.0,57.9,-11.0,42.2,-1.0,0.50
20011,2339810,2020-02-26,Mirage,13.0,3.0,19.0,9.0,0.0,57.7,-6.0,63.2,3.0,0.85

In [16]:
# Indivdual player stat cumulative average for every map
pk_cum_avg_kills = pk.groupby(['player_id','map']).kills.apply(lambda x : x.expanding(min_periods=1).mean().fillna(x))
pk_cum_avg_assists = pk.groupby(['player_id','map']).assists.apply(lambda x : x.expanding(min_periods=1).mean().fillna(x))
pk_cum_avg_deaths = pk.groupby(['player_id','map']).deaths.apply(lambda x : x.expanding(min_periods=1).mean().fillna(x))
pk_cum_avg_hs = pk.groupby(['player_id','map']).hs.apply(lambda x : x.expanding(min_periods=1).mean().fillna(x))
pk_cum_avg_flash_assists = pk.groupby(['player_id','map']).flash_assists.apply(lambda x : x.expanding(min_periods=1).mean().fillna(x))
pk_cum_avg_kast = pk.groupby(['player_id','map']).kast.apply(lambda x : x.expanding(min_periods=1).mean().fillna(x))
pk_cum_avg_kddiff = pk.groupby(['player_id','map']).kddiff.apply(lambda x : x.expanding(min_periods=1).mean().fillna(x))
pk_cum_avg_adr = pk.groupby(['player_id','map']).adr.apply(lambda x : x.expanding(min_periods=1).mean().fillna(x))
pk_cum_avg_fkdiff = pk.groupby(['player_id','map']).fkdiff.apply(lambda x : x.expanding(min_periods=1).mean().fillna(x))

In [21]:
pk_cum_avg_rating = pk.groupby(['player_id','map']).rating.apply(lambda x : x.expanding(min_periods=1).mean().fillna(x))

In [35]:
pk.loc[:,'Rating_Avg_Per_Map'] = pk_cum_avg_rating

In [17]:
pk.loc[:,'Kill_Avg_Per_Map'] = pk_cum_avg_kills
pk.loc[:,'Assits_Avg_Per_Map'] = pk_cum_avg_assists
pk.loc[:,'Deaths_Avg_Per_Map'] = pk_cum_avg_deaths
pk.loc[:,'HS_Avg_Per_Map'] = pk_cum_avg_hs
pk.loc[:,'Assists_Avg_Per_Map'] = pk_cum_avg_flash_assists
pk.loc[:,'Kast_Avg_Per_Map'] = pk_cum_avg_kast
pk.loc[:,'Kddiff_Avg_Per_Map'] = pk_cum_avg_kddiff
pk.loc[:,'ADR_Avg_Per_Map'] = pk_cum_avg_adr
pk.loc[:,'FKdiff_Avg_Per_Map'] = pk_cum_avg_fkdiff

In [36]:
player_running_averages = pd.merge(player_running_averages,pk, on=['player_id','match_id','date','map','kills','assists','deaths','hs','flash_assists','kast','kddiff','adr','fkdiff','rating'])

In [37]:
player_running_averages = player_running_averages.sort_values(['player_id','date'])

In [38]:
pk = player_running_averages[['player_id','match_id','date','map','kills','assists','deaths','hs','flash_assists','kast','kddiff','adr','fkdiff','rating']]

In [39]:
pk = pk.set_index('player_id')

In [40]:
pk_overall_avg_rating = pk.groupby(['player_id']).rating.apply(lambda x : x.expanding(min_periods=1).mean().fillna(x))

In [22]:
# Individual players stat cumulative average from earliest date to most current
pk_overall_avg_kills = pk.groupby(['player_id']).kills.apply(lambda x : x.expanding(min_periods=1).mean().fillna(x))
pk_overall_avg_assists = pk.groupby(['player_id']).assists.apply(lambda x : x.expanding(min_periods=1).mean().fillna(x))
pk_overall_avg_deaths = pk.groupby(['player_id']).deaths.apply(lambda x : x.expanding(min_periods=1).mean().fillna(x))
pk_overall_avg_hs = pk.groupby(['player_id']).hs.apply(lambda x : x.expanding(min_periods=1).mean().fillna(x))
pk_overall_avg_flash_assists = pk.groupby(['player_id']).flash_assists.apply(lambda x : x.expanding(min_periods=1).mean().fillna(x))
pk_overall_avg_kast = pk.groupby(['player_id']).kast.apply(lambda x : x.expanding(min_periods=1).mean().fillna(x))
pk_overall_avg_kddiff = pk.groupby(['player_id']).kddiff.apply(lambda x : x.expanding(min_periods=1).mean().fillna(x))
pk_overall_avg_adr = pk.groupby(['player_id']).adr.apply(lambda x : x.expanding(min_periods=1).mean().fillna(x))
pk_overall_avg_fkdiff = pk.groupby(['player_id']).fkdiff.apply(lambda x : x.expanding(min_periods=1).mean().fillna(x))

In [41]:
pk.loc[:,'Rating_Avg_Overall'] = pk_overall_avg_rating

In [23]:
pk.loc[:,'Kill_Avg_Overall'] = pk_overall_avg_kills
pk.loc[:,'Assits_Avg_Overall'] = pk_overall_avg_assists
pk.loc[:,'Deaths_Avg_Overall'] = pk_overall_avg_deaths
pk.loc[:,'HS_Avg_Overall'] = pk_overall_avg_hs
pk.loc[:,'Assists_Avg_Overall'] = pk_overall_avg_flash_assists
pk.loc[:,'Kast_Avg_Overall'] = pk_overall_avg_kast
pk.loc[:,'Kddiff_Avg_Overall'] = pk_overall_avg_kddiff
pk.loc[:,'ADR_Avg_Overall'] = pk_overall_avg_adr
pk.loc[:,'FKdiff_Avg_Overall'] = pk_overall_avg_fkdiff

In [44]:
player_running_averages = pd.merge(player_running_averages,pk, on=['player_id','match_id','date','map','kills','assists','deaths','hs','flash_assists','kast','kddiff','adr','fkdiff','rating'])

In [43]:
player_running_averages

,date,player_name,team,opponent,player_id,match_id,event_id,best_of,map,kills,...,deaths,hs,flash_assists,kast,kddiff,adr,fkdiff,rating,Rating_Avg_Per_Map,Rating_Avg_Overall
0,2016-03-10,Friis,SK,E-frag.net,7,2301254,2165,1,Overpass,21.0,...,25.0,2.0,0.0,61.1,-4.0,52.2,2.0,0.83,0.83,0.830000
1,2016-03-12,Friis,SK,FaZe,7,2301112,2124,1,Cache,34.0,...,29.0,3.0,0.0,75.0,5.0,63.8,1.0,1.08,1.08,0.955000
2,2016-03-13,Friis,SK,Ancient,7,2301320,2173,3,Mirage,22.0,...,25.0,6.0,0.0,66.7,-3.0,62.3,0.0,0.95,0.95,0.953333
3,2016-03-15,Friis,SK,Tricked,7,2301358,2119,3,Overpass,23.0,...,24.0,2.0,0.0,66.7,-1.0,63.8,3.0,1.01,0.92,0.967500
4,2016-03-19,Friis,SK,NiP,7,2301377,2124,1,Mirage,26.0,...,24.0,4.0,0.0,77.1,2.0,82.2,5.0,1.23,1.09,1.020000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448706,2020-02-23,rabbit,Titan,Medieval,20006,2339752,5230,3,Nuke,26.0,...,14.0,13.0,0.0,85.2,12.0,92.7,1.0,1.42,1.42,1.142000
448707,2020-02-23,boskacz,Wisla Krakow,BIG,20007,2339745,5150,1,Nuke,3.0,...,16.0,0.0,1.0,22.2,-13.0,19.7,-2.0,0.24,0.24,0.240000
448708,2020-02-27,Porky,LND,Rysix,20009,2339813,5233,1,Vertigo,14.0,...,16.0,7.0,0.0,57.9,-2.0,86.5,0.0,0.93,0.93,0.930000
448709,2020-02-27,shevi,LND,Rysix,20010,2339813,5233,1,Vertigo,6.0,...,17.0,5.0,0.0,57.9,-11.0,42.2,-1.0,0.50,0.50,0.500000
448710,2020-02-26,bichop,FREEROX,Sinisters,20011,2339810,5233,1,Mirage,13.0,...,19.0,9.0,0.0,57.7,-6.0,63.2,3.0,0.85,0.85,0.850000

In [43]:
pd.set_option('display.max_columns', None)
player_running_averages

,date,player_name,team,opponent,player_id,match_id,event_id,best_of,map,kills,assists,deaths,hs,flash_assists,kast,kddiff,adr,fkdiff,rating,Kill_Avg_Per_Map,Assits_Avg_Per_Map,Deaths_Avg_Per_Map,HS_Avg_Per_Map,Assists_Avg_Per_Map,Kast_Avg_Per_Map,Kddiff_Avg_Per_Map,ADR_Avg_Per_Map,FKdiff_Avg_Per_Map,Kill_Avg_Overall,Assits_Avg_Overall,Deaths_Avg_Overall,HS_Avg_Overall,Assists_Avg_Overall,Kast_Avg_Overall,Kddiff_Avg_Overall,ADR_Avg_Overall,FKdiff_Avg_Overall
0,2016-03-10,Friis,SK,E-frag.net,7,2301254,2165,1,Overpass,21.0,0.0,25.0,2.0,0.0,61.1,-4.0,52.2,2.0,0.83,21.0,0.0,25.0,2.0,0.0,61.1,-4.0,52.20,2.0,21.000000,0.000000,25.000000,2.000000,0.0,61.100,-4.000000,52.200000,2.0
1,2016-03-12,Friis,SK,FaZe,7,2301112,2124,1,Cache,34.0,5.0,29.0,3.0,0.0,75.0,5.0,63.8,1.0,1.08,34.0,5.0,29.0,3.0,0.0,75.0,5.0,63.80,1.0,27.500000,2.500000,27.000000,2.500000,0.0,68.050,0.500000,58.000000,1.5
2,2016-03-13,Friis,SK,Ancient,7,2301320,2173,3,Mirage,22.0,5.0,25.0,6.0,0.0,66.7,-3.0,62.3,0.0,0.95,22.0,5.0,25.0,6.0,0.0,66.7,-3.0,62.30,0.0,25.666667,3.333333,26.333333,3.666667,0.0,67.600,-0.666667,59.433333,1.0
3,2016-03-15,Friis,SK,Tricked,7,2301358,2119,3,Overpass,23.0,2.0,24.0,2.0,0.0,66.7,-1.0,63.8,3.0,1.01,22.0,1.0,24.5,2.0,0.0,63.9,-2.5,58.00,2.5,25.000000,3.000000,25.750000,3.250000,0.0,67.375,-0.750000,60.525000,1.5
4,2016-03-19,Friis,SK,NiP,7,2301377,2124,1,Mirage,26.0,8.0,24.0,4.0,0.0,77.1,2.0,82.2,5.0,1.23,24.0,6.5,24.5,5.0,0.0,71.9,-0.5,72.25,2.5,25.200000,4.000000,25.400000,3.400000,0.0,69.320,-0.200000,64.860000,2.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448706,2020-02-23,rabbit,Titan,Medieval,20006,2339752,5230,3,Nuke,26.0,3.0,14.0,13.0,0.0,85.2,12.0,92.7,1.0,1.42,26.0,3.0,14.0,13.0,0.0,85.2,12.0,92.70,1.0,20.600000,3.800000,18.200000,10.600000,0.4,77.560,2.400000,72.740000,0.6
448707,2020-02-23,boskacz,Wisla Krakow,BIG,20007,2339745,5150,1,Nuke,3.0,1.0,16.0,0.0,1.0,22.2,-13.0,19.7,-2.0,0.24,3.0,1.0,16.0,0.0,1.0,22.2,-13.0,19.70,-2.0,3.000000,1.000000,16.000000,0.000000,1.0,22.200,-13.000000,19.700000,-2.0
448708,2020-02-27,Porky,LND,Rysix,20009,2339813,5233,1,Vertigo,14.0,0.0,16.0,7.0,0.0,57.9,-2.0,86.5,0.0,0.93,14.0,0.0,16.0,7.0,0.0,57.9,-2.0,86.50,0.0,14.000000,0.000000,16.000000,7.000000,0.0,57.900,-2.000000,86.500000,0.0
448709,2020-02-27,shevi,LND,Rysix,20010,2339813,5233,1,Vertigo,6.0,1.0,17.0,5.0,0.0,57.9,-11.0,42.2,-1.0,0.50,6.0,1.0,17.0,5.0,0.0,57.9,-11.0,42.20,-1.0,6.000000,1.000000,17.000000,5.000000,0.0,57.900,-11.000000,42.200000,-1.0
448710,2020-02-26,bichop,FREEROX,Sinisters,20011,2339810,5233,1,Mirage,13.0,3.0,19.0,9.0,0.0,57.7,-6.0,63.2,3.0,0.85,13.0,3.0,19.0,9.0,0.0,57.7,-6.0,63.20,3.0,13.000000,3.000000,19.000000,9.000000,0.0,57.700,-6.000000,63.200000,3.0

In [34]:
player_running_averages.columns

Index(['date', 'player_name', 'team', 'opponent', 'player_id', 'match_id',
       'event_id', 'best_of', 'map', 'kills', 'assists', 'deaths', 'hs',
       'flash_assists', 'kast', 'kddiff', 'adr', 'fkdiff', 'rating',
       'Kill_Avg_Per_Map', 'Assits_Avg_Per_Map', 'Deaths_Avg_Per_Map',
       'HS_Avg_Per_Map', 'Assists_Avg_Per_Map', 'Kast_Avg_Per_Map',
       'Kddiff_Avg_Per_Map', 'ADR_Avg_Per_Map', 'FKdiff_Avg_Per_Map',
       'Kill_Avg_Overall', 'Assits_Avg_Overall', 'Deaths_Avg_Overall',
       'HS_Avg_Overall', 'Assists_Avg_Overall', 'Kast_Avg_Overall',
       'Kddiff_Avg_Overall', 'ADR_Avg_Overall', 'FKdiff_Avg_Overall'],
      dtype='object')

In [35]:
column_headers = ['match_id','date', 'player_name', 'team', 'opponent', 'player_id',
       'event_id', 'best_of', 'map', 'kills', 'assists', 'deaths', 'hs',
       'flash_assists', 'kast', 'kddiff', 'adr', 'fkdiff', 'rating',
       'Kill_Avg_Per_Map', 'Assits_Avg_Per_Map', 'Deaths_Avg_Per_Map',
       'HS_Avg_Per_Map', 'Assists_Avg_Per_Map', 'Kast_Avg_Per_Map',
       'Kddiff_Avg_Per_Map', 'ADR_Avg_Per_Map', 'FKdiff_Avg_Per_Map',
       'Kill_Avg_Overall', 'Assits_Avg_Overall', 'Deaths_Avg_Overall',
       'HS_Avg_Overall', 'Assists_Avg_Overall', 'Kast_Avg_Overall',
       'Kddiff_Avg_Overall', 'ADR_Avg_Overall', 'FKdiff_Avg_Overall']

In [36]:
import datetime

player_running_averages['date'] = pd.to_datetime(player_running_averages['date'])

In [45]:
player_running_averages2 = pd.merge(player_running_averages,pk, on=['player_id','match_id','date','map','kills','assists','deaths','hs','flash_assists','kast','kddiff','adr','fkdiff','rating'])

In [46]:
import datetime

player_running_averages2['date'] = pd.to_datetime(player_running_averages2['date'])

In [37]:
player_running_averages = player_running_averages[column_headers]
player_running_averages.dtypes

match_id                        int64
date                   datetime64[ns]
player_name                    object
team                           object
opponent                       object
player_id                       int64
event_id                        int64
best_of                         int64
map                            object
kills                         float64
assists                       float64
deaths                        float64
hs                            float64
flash_assists                 float64
kast                          float64
kddiff                        float64
adr                           float64
fkdiff                        float64
rating                        float64
Kill_Avg_Per_Map              float64
Assits_Avg_Per_Map            float64
Deaths_Avg_Per_Map            float64
HS_Avg_Per_Map                float64
Assists_Avg_Per_Map           float64
Kast_Avg_Per_Map              float64
Kddiff_Avg_Per_Map            float64
ADR_Avg_Per_Map               float64
FKdiff_Avg_Per_Map            float64
Kill_Avg_Overall              float64
Assits_Avg_Overall            float64
Deaths_Avg_Overall            float64
HS_Avg_Overall                float64
Assists_Avg_Overall           float64
Kast_Avg_Overall              float64
Kddiff_Avg_Overall            float64
ADR_Avg_Overall               float64
FKdiff_Avg_Overall            float64
dtype: object

In [55]:
player_running_averages

,match_id,date,player_name,team,opponent,player_id,event_id,best_of,map,kills,assists,deaths,hs,flash_assists,kast,kddiff,adr,fkdiff,rating,Kill_Avg_Per_Map,Assits_Avg_Per_Map,Deaths_Avg_Per_Map,HS_Avg_Per_Map,Assists_Avg_Per_Map,Kast_Avg_Per_Map,Kddiff_Avg_Per_Map,ADR_Avg_Per_Map,FKdiff_Avg_Per_Map,Kill_Avg_Overall,Assits_Avg_Overall,Deaths_Avg_Overall,HS_Avg_Overall,Assists_Avg_Overall,Kast_Avg_Overall,Kddiff_Avg_Overall,ADR_Avg_Overall,FKdiff_Avg_Overall
0,2301254,2016-03-10,Friis,SK,E-frag.net,7,2165,1,Overpass,21.0,0.0,25.0,2.0,0.0,61.1,-4.0,52.2,2.0,0.83,21.0,0.0,25.0,2.0,0.0,61.1,-4.0,52.20,2.0,21.000000,0.000000,25.000000,2.000000,0.0,61.100,-4.000000,52.200000,2.0
1,2301112,2016-03-12,Friis,SK,FaZe,7,2124,1,Cache,34.0,5.0,29.0,3.0,0.0,75.0,5.0,63.8,1.0,1.08,34.0,5.0,29.0,3.0,0.0,75.0,5.0,63.80,1.0,27.500000,2.500000,27.000000,2.500000,0.0,68.050,0.500000,58.000000,1.5
2,2301320,2016-03-13,Friis,SK,Ancient,7,2173,3,Mirage,22.0,5.0,25.0,6.0,0.0,66.7,-3.0,62.3,0.0,0.95,22.0,5.0,25.0,6.0,0.0,66.7,-3.0,62.30,0.0,25.666667,3.333333,26.333333,3.666667,0.0,67.600,-0.666667,59.433333,1.0
3,2301358,2016-03-15,Friis,SK,Tricked,7,2119,3,Overpass,23.0,2.0,24.0,2.0,0.0,66.7,-1.0,63.8,3.0,1.01,22.0,1.0,24.5,2.0,0.0,63.9,-2.5,58.00,2.5,25.000000,3.000000,25.750000,3.250000,0.0,67.375,-0.750000,60.525000,1.5
4,2301377,2016-03-19,Friis,SK,NiP,7,2124,1,Mirage,26.0,8.0,24.0,4.0,0.0,77.1,2.0,82.2,5.0,1.23,24.0,6.5,24.5,5.0,0.0,71.9,-0.5,72.25,2.5,25.200000,4.000000,25.400000,3.400000,0.0,69.320,-0.200000,64.860000,2.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448706,2339752,2020-02-23,rabbit,Titan,Medieval,20006,5230,3,Nuke,26.0,3.0,14.0,13.0,0.0,85.2,12.0,92.7,1.0,1.42,26.0,3.0,14.0,13.0,0.0,85.2,12.0,92.70,1.0,20.600000,3.800000,18.200000,10.600000,0.4,77.560,2.400000,72.740000,0.6
448707,2339745,2020-02-23,boskacz,Wisla Krakow,BIG,20007,5150,1,Nuke,3.0,1.0,16.0,0.0,1.0,22.2,-13.0,19.7,-2.0,0.24,3.0,1.0,16.0,0.0,1.0,22.2,-13.0,19.70,-2.0,3.000000,1.000000,16.000000,0.000000,1.0,22.200,-13.000000,19.700000,-2.0
448708,2339813,2020-02-27,Porky,LND,Rysix,20009,5233,1,Vertigo,14.0,0.0,16.0,7.0,0.0,57.9,-2.0,86.5,0.0,0.93,14.0,0.0,16.0,7.0,0.0,57.9,-2.0,86.50,0.0,14.000000,0.000000,16.000000,7.000000,0.0,57.900,-2.000000,86.500000,0.0
448709,2339813,2020-02-27,shevi,LND,Rysix,20010,5233,1,Vertigo,6.0,1.0,17.0,5.0,0.0,57.9,-11.0,42.2,-1.0,0.50,6.0,1.0,17.0,5.0,0.0,57.9,-11.0,42.20,-1.0,6.000000,1.000000,17.000000,5.000000,0.0,57.900,-11.000000,42.200000,-1.0
448710,2339810,2020-02-26,bichop,FREEROX,Sinisters,20011,5233,1,Mirage,13.0,3.0,19.0,9.0,0.0,57.7,-6.0,63.2,3.0,0.85,13.0,3.0,19.0,9.0,0.0,57.7,-6.0,63.20,3.0,13.000000,3.000000,19.000000,9.000000,0.0,57.700,-6.000000,63.200000,3.0

In [33]:
import sqlalchemy  # Package for accessing SQL databases via Python
import psycopg2

# Connect to database (Note: The package psychopg2 is required for Postgres to work with SQLAlchemy)
engine = sqlalchemy.create_engine(f"postgresql://postgres:{password}@dataviz.cdhexjpu5mat.us-east-2.rds.amazonaws.com:{port}/CSGO_project")
con = engine.connect()

# Verify that there are no existing tables
print(engine.table_names())

['Matches', 'Maps', 'Team_results', 'Players']

In [47]:
player_running_averages.to_csv('players_extended_stats_rating_addition.csv')

In [39]:
player_running_averages.to_csv('players_extended_stats.csv')

In [ ]:
import time
table_name = 'Players'
start_time = time.time()
player_running_averages.to_sql(table_name, con, if_exists='replace',method='multi', index=False)
print("--- %s seconds ---" % (time.time() - start_time))